spring:
  application:
    name: demo-spring-feign-server

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka.test.com:8761/eureka/

logging:
  level:
    org.springframework: debug
