server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.test.com:3306/seata?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&tinyInt1isBit=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false

  redis:
    host: redis.test.com
    port: 6379
    password: aliredis

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: debug
