server:
  port: 8080

spring:
  application:
    name: demo-eureka-ribbon-client

ribbon:
  eureka:
    enabled: true

demo-eureka-ribbon-service:
  ribbon:
    # 这个是配置ribbon内，定时刷新registry的间隔，demo-eureka-ribbon-service是被调用的服务名
    ServerListRefreshInterval: 2000

eureka:
  # ======== org.springframework.cloud.netflix.eureka.EurekaClientConfigBean =======
  client:
    registry-fetch-interval-seconds: 50
    service-url:
      defaultZone: http://localhost:9090/eureka/
  # ======== EurekaClientConfigBean =======


logging:
  level:
    org.springframework: debug
    com.netflix: debug
