server:
  port: 8081

spring:
  application:
    name: gateway-destination-service

  cloud:
    gateway:
      httpclient:
        response-timeout: 45s
      routes:
        - id: test
          order: -100
          uri: lb://gateway-target-service
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka.test.com:8761/eureka/

logging:
  level:
    root: OFF

